-- Day zero schema for the CineLog app database.
-- Matches current JPA entities. PostgreSQL only. No seed data.

-- users
CREATE TABLE users (
    id                   INTEGER GENERATED BY DEFAULT AS IDENTITY,
    username             VARCHAR(255)      NOT NULL,
    password             VARCHAR(255)      NOT NULL,
    email                VARCHAR(254),
    profile_picture_url  VARCHAR(1024),
    rec_scope            VARCHAR(16),
    rec_min_score        DOUBLE PRECISION,
    rec_max_results      INTEGER,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT uk_users_username UNIQUE (username),
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT users_rec_scope_check CHECK (rec_scope IN ('ALL', 'MOVIE', 'TV'))
);

-- refresh_tokens
CREATE TABLE refresh_tokens (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id                INTEGER      NOT NULL,
    token_hash             VARCHAR(64)  NOT NULL,
    family_id              VARCHAR(255) NOT NULL,
    created_at             TIMESTAMPTZ  NOT NULL,
    expires_at             TIMESTAMPTZ  NOT NULL,
    revoked_at             TIMESTAMPTZ,
    replaced_by_token_hash VARCHAR(64),
    CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id),
    CONSTRAINT uk_refresh_tokens_token_hash UNIQUE (token_hash),
    CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX idx_refresh_tokens_user_id ON refresh_tokens (user_id);

-- user_list_entries
CREATE TABLE user_list_entries (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id    INTEGER     NOT NULL,
    tmdb_id    INTEGER     NOT NULL,
    media_type VARCHAR(16) NOT NULL,
    list_type  VARCHAR(16) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT user_list_entries_pkey PRIMARY KEY (id),
    CONSTRAINT uk_user_list_entry UNIQUE (user_id, tmdb_id, media_type, list_type),
    CONSTRAINT user_list_entries_media_type_check CHECK (media_type IN ('MOVIE', 'TV')),
    CONSTRAINT user_list_entries_list_type_check CHECK (list_type IN ('WATCHLIST', 'WATCHED', 'LOVED', 'REJECTED')),
    CONSTRAINT fk_user_list_entries_user FOREIGN KEY (user_id) REFERENCES users (id)
);

-- user_recommendation
CREATE TABLE user_recommendation (
    user_id    INTEGER     NOT NULL,
    tmdb_id    INTEGER     NOT NULL,
    media_type VARCHAR(16) NOT NULL,
    CONSTRAINT user_recommendation_media_type_check CHECK (media_type IN ('MOVIE', 'TV')),
    CONSTRAINT fk_user_recommendation_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX idx_user_recommendation_user_id ON user_recommendation (user_id);

-- movies
CREATE TABLE movies (
    id                INTEGER,
    adult             BOOLEAN,
    backdrop_path     VARCHAR(255),
    original_language VARCHAR(255),
    original_title    VARCHAR(255),
    overview          VARCHAR(2048),
    popularity        DOUBLE PRECISION,
    poster_path       VARCHAR(255),
    release_date      DATE,
    title             VARCHAR(255),
    video             BOOLEAN,
    vote_average      DOUBLE PRECISION,
    vote_count        INTEGER,
    CONSTRAINT movies_pkey PRIMARY KEY (id)
);

-- movie_genres
CREATE TABLE movie_genres (
    movie_id INTEGER NOT NULL,
    genre_id INTEGER NOT NULL,
    CONSTRAINT fk_movie_genres_movie FOREIGN KEY (movie_id) REFERENCES movies (id)
);

CREATE INDEX idx_movie_genres_movie_id ON movie_genres (movie_id);

-- tv_shows
CREATE TABLE tv_shows (
    id                INTEGER,
    adult             BOOLEAN,
    backdrop_path     VARCHAR(255),
    original_language VARCHAR(255),
    original_title    VARCHAR(255),
    overview          VARCHAR(2048),
    popularity        DOUBLE PRECISION,
    poster_path       VARCHAR(255),
    release_date      DATE,
    title             VARCHAR(255),
    vote_average      DOUBLE PRECISION,
    vote_count        INTEGER,
    CONSTRAINT tv_shows_pkey PRIMARY KEY (id)
);

-- tv_show_genres
CREATE TABLE tv_show_genres (
    tv_show_id INTEGER NOT NULL,
    genre_id   INTEGER NOT NULL,
    CONSTRAINT fk_tv_show_genres_tv_show FOREIGN KEY (tv_show_id) REFERENCES tv_shows (id)
);

CREATE INDEX idx_tv_show_genres_tv_show_id ON tv_show_genres (tv_show_id);

-- tv_show_origin_country
CREATE TABLE tv_show_origin_country (
    tv_show_id     INTEGER      NOT NULL,
    origin_country VARCHAR(255) NOT NULL,
    CONSTRAINT fk_tv_show_origin_country_tv_show FOREIGN KEY (tv_show_id) REFERENCES tv_shows (id)
);

CREATE INDEX idx_tv_show_origin_country_tv_show_id ON tv_show_origin_country (tv_show_id);

-- catalog_cache
CREATE TABLE catalog_cache (
    tmdb_id      INTEGER      NOT NULL,
    media_type   VARCHAR(16)  NOT NULL,
    title        VARCHAR(255) NOT NULL,
    poster_path  VARCHAR(255),
    release_date DATE,
    overview     VARCHAR(2048),
    created_at   TIMESTAMPTZ  NOT NULL,
    updated_at   TIMESTAMPTZ  NOT NULL,
    CONSTRAINT catalog_cache_pkey PRIMARY KEY (tmdb_id, media_type),
    CONSTRAINT catalog_cache_media_type_check CHECK (media_type IN ('MOVIE', 'TV'))
);
